CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C                                                                       C
C PROGRAMA PARA CALCULAR: VALORES MEDIOS DE PARAMETROS COLETADOS        C
C NA ESTACAO METEOROLOGICA DE SAO ROQUE e NA ESTACAO BALSA.             C
C    PROGRAMA CALCULA MEDIAS  										  C
C    HORARIAS DE PARAMETROS QUE SAO REGISTRADOS A  INTERVALOS DE        C
C    5 MINUTOS. CONFORME PROGRAMACAO, OS DADOS SAO LIDOS A CADA		  C
C    3 SEGUNDOS E OS VALORES MEDIOS REGISTRADOS A CADA 5 MINUT0S  	  C
C																	  C
C ADAPTACAO FEITA EM MARCO DE 2005 EM S.MARIA, PARA TRABALHAR COM  	  C
C    OS DADOS DE SÃO ROQUE E BALSA DEPOIS DE PROBLEMA OCORRIDO          C
C    EM SROQUE, EM DEZEMMBRO DE 2004. O RODRIGO DA SILVA E O OTAVIO     C
C    FIZERAM O CONCERTO DA ESTACAO E COLOCARAM NAS DUAS O MESMO         C
C    DE MODO QUE A ESTRUTURA DOS ARQUIVOS, EM AMBAS AS ESTACOES         C
C    É A MESMA. POR ISTO, AGORA, É POSSIVEL USAR O MESMO PROGRAMA       C
C    PARA CALCULO DE VALORES MEDIOS. 									  C
C																	  C
C                     Nova roma do Sul, 9 de abril de 2005              C
C																	  C	
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C 
	PARAMETER(N=200000)
	CHARACTER A*1,V*1,B*1,FNAME*30
	REAL OLDINPUT(N,9)	   
	REAL TES(N,7),DIV(N)
C
COLOCADO AQUI O PRIMEIRO TESTE PARA LER OS DADOS BRUTOS
C
	DIMENSION A(200),FNAME(1000)
C       
C	REAL SOMA(10),MEDIO(10)
C
	OPEN(UNIT=22,FILE='MEDIA.DAT')
      OPEN(UNIT=19,FILE='BRUTOS.DAT')
cC========================================================
C LEITURA DOS NOMES DOS ARQUIVOS QUE SERAO ANALIZADOS
C========================================================
        READ(19,1004)NK
1004    FORMAT(I3)
	DO 300 L=1,NK
        READ(19,1013)FNAME(L)
1013	FORMAT(A11)
C========================================================
        OPEN(UNIT=20,FILE=FNAME(L))
	V=','
        B=' '
C       NL = NUMERO DE LINHAS COM DADOS DE CADA ARQUIVO
C	NLL= NUMERO DE LINHAS COM DADOS DO ARQUIVO COMPOSTO
	NL=0
	I=0
88	I=I+1
        READ(20,1001,END=99)A
1001    FORMAT(200A1)
C
        DO 100 J=1,200
        IF(A(J).EQ.V)A(J)=B
100     CONTINUE
C
        OPEN(UNIT=21,FILE='TRATADOS.DAT')
C
	IF(A(1).EQ.B)GO TO 88
        NL=NL+1
C
C====================================================================
C
C 111 = CODIGO REFERENTE VALORES BRUTOS MEDIDOS FREQ.=1HZ
        IF(A(1).EQ.'1'.AND.A(2).EQ.'1'.AND.A(3).EQ.'9')WRITE(21,1001)A
C
C
        GO TO 88
99      CONTINUE
300     CONTINUE
        CLOSE(21)
C======================================================================
	OPEN(UNIT=11,FILE='OLDINPUT.DAT')
      OPEN(UNIT=23,FILE='TRATADOS.DAT')
C==============================================
C       LEITURA DO ARQUIVO SEM VIRGULA='TRATADOS.DAT'
C==============================================
C
c      LIXT1=0.
c	LIXT2=0.
	DO 4321 L=1,N
        READ(23,*,END=1)NC
        IF(NC.EQ.119) GO TO 1112
1112    BACKSPACE 23
	READ(23,*,END=299)NC,ANO,DJ,HHMM,VM,DM,DIRSTD,VY1,DY1,
	& RAD,TEMP,UR,TSOLO,PR,CHUVA,USTD,TSTD,UMAX,TMAX,UMIN,TMIN
	WRITE(11,*)DJ,INT(HHMM/100.),VM,DM,RAD,TEMP,UR,TSOLO,PR,CHUVA
        GO TO 122
122	CONTINUE
C
1     CONTINUE
	
4321  CONTINUE
299	CONTINUE
	CLOSE(23)
	CLOSE(11)
c      
	OPEN(UNIT=11,FILE='OLDINPUT.DAT',STATUS='UNKNOWN')
CCC  LE  ARQUIVO DE ENTRADA
	DO 10 I=1,N
	READ (11,*,END=10)(OLDINPUT(I,J),J=1,10)
10    CONTINUE
C 
      K=1
	DIV(K)=1
	TES(K,1)=OLDINPUT(1,3)
	TES(K,2)=OLDINPUT(1,4)
	TES(K,3)=OLDINPUT(1,5)
	TES(K,4)=OLDINPUT(1,6)
	TES(K,5)=OLDINPUT(1,7)
	TES(K,6)=OLDINPUT(1,8)
	TES(K,7)=OLDINPUT(1,9)
	TES(K,8)=OLDINPUT(1,10)
C	TES(K,9)=OLDINPUT(1,11)
C	TES(K,10)=OLDINPUT(1,12)
	DO 11 I=1,N
	    IF(OLDINPUT(I+1,2).EQ.OLDINPUT(I,2))THEN
	       DIV(K)=DIV(K)+1
	       TES(K,1)=TES(K,1)+OLDINPUT(I+1,3)
	       TES(K,2)=TES(K,2)+OLDINPUT(I+1,4)
	       TES(K,3)=TES(K,3)+OLDINPUT(I+1,5)
	       TES(K,4)=TES(K,4)+OLDINPUT(I+1,6)
             TES(K,5)=TES(K,5)+OLDINPUT(I+1,7)
	       TES(K,6)=TES(K,6)+OLDINPUT(I+1,8)
	       TES(K,7)=TES(K,7)+OLDINPUT(I+1,9)
	       TES(K,8)=TES(K,8)+OLDINPUT(I+1,10)
C	       TES(K,9)=TES(K,9)+OLDINPUT(I+1,11)
C             TES(K,10)=TES(K,10)+OLDINPUT(I+1,12)
	    ELSE
	       K=K+1
	       DIV(K)=1
	       TES(K,1)=TES(K,1)+OLDINPUT(I+1,3)
	       TES(K,2)=TES(K,2)+OLDINPUT(I+1,4)
	       TES(K,3)=TES(K,3)+OLDINPUT(I+1,5)
	       TES(K,4)=TES(K,4)+OLDINPUT(I+1,6)
             TES(K,5)=TES(K,5)+OLDINPUT(I+1,7)
	       TES(K,6)=TES(K,6)+OLDINPUT(I+1,8)
	       TES(K,7)=TES(K,7)+OLDINPUT(I+1,9)
	       TES(K,8)=TES(K,8)+OLDINPUT(I+1,10)
C	       TES(K,9)=TES(K,9)+OLDINPUT(I+1,11)
C            TES(K,10)=TES(K,10)+OLDINPUT(I+1,12)
		ENDIF
11    CONTINUE
C      PRINT*,'ESTOU AQUI'
      VAR=0
      DO 12 K=1,10000
C	PRINT*,K
	VAR=VAR+DIV(K)
	WRITE(22,1172)OLDINPUT(VAR,1),OLDINPUT(VAR,2),TES(K,1)/DIV(K),
	& TES(K,2)/DIV(K),TES(K,3)/DIV(K),TES(K,4)/DIV(K),TES(K,5)/DIV(K),
	& TES(K,6)/DIV(K),TES(K,7)/DIV(K),TES(K,8)
c     ,TES(K,8)/DIV(K),TES(K,9)/DIV(K),TES(K,10)/DIV(K)
1172  FORMAT(2X,F5.0,2X,F5.0,2X,F9.4,2X,F9.4,2X,F9.4,2X,F9.4,2X,F9.4,
     &                       2X,F9.4,2X,F9.4,2X,F8.2)
12    CONTINUE
C
      CLOSE(22)
      STOP
     	END



