#!/bin/bash
for x in *.dat
do
clear
#  hi=`echo $x | cut -c2-3`
#  mi=`echo $x | cut -c4-5`
#  hf=`echo $x | cut -c7-8`
#  mf=`echo $x | cut -c9-10`
   dia=`echo $x | cut -c9-10`
#  mes=`echo $x | cut -c14-15`
#  ano=`echo $x | cut -c16-17`

rm -f INPUT.DAT
cp $x INPUT.DAT
echo ">>executing $x...."
./pasturehans.x77
echo '>>>>>executed ...'
 for spc in S*
 do
# compact bad file 
# gzip $x 
# move compressed an renomed bad file
# to specific bad files folder  
   tipo=`echo $spc | cut -c1-4`
   cp $spc F$tipo.D$dia

# call external batches
## limpalog clean log file an move files with 22 colummns
## to extracted raw specific folder
## leraw22.sh extracts 22 raw colummns from raw 79 colummns files
#    ./limpalog
#    ./leraw22.sh  
done 
done
