#!/bin/bash
geragpl()
{
echo "\\n gerando gráficos... \\n"
cat<<eogpl>MEDIO.GPL

set encoding iso_8859_1
set term postscript enhanced "arial" 12
set logscale
set style line 4
set pointsize 0.5
set output '$tip-B$BANDAS-$classe-$anomes.eps'
set ylabel "nS_{uvw}/u@^{2}_* {/Symbol f}^{2/3}"
set xlabel "f=nz/U"
set title 'Espectros medios 15 dias. $classe $anomes - STM/km77 | BANDAS: $BANDAS | Trat: $tip'
p 'M$tip-$classe-$anomes.spc' u 1:2 w lp ti 'S_u' 4,'' u 1:3 w lp ti 'S_v' 3,'' u 1:4 w lp ti 'S_w' 2

eogpl
gnuplot 'MEDIO.GPL'
convert $tip-B$BANDAS-$classe-$anomes.eps $tip-B$BANDAS-$classe-$anomes.pdf
#gv $tip-B$BANDAS-$classe-$anomes.pdf &
return
}


if [ $# -ne 2 ]; then

 echo "";echo "Usage: $0 filename bandsize";echo ""
 echo " $USER! Digite o nome do arquivo com a classe e o numero de bandas para suavizar."
 echo " Exemplo: $0 SCC1-2002-03.spc 20";echo ""
 else
clear
rm -f tmpspc.dat
BANDAS=$2
classe=`echo $1 | cut -c11-14`
anomes=`echo $1 | cut -c16-22`
tip=`echo $1 | cut -c5-9`
fourcol='tmpspc.dat'

L=`wc -l $1 | awk '{print $1}'`
echo " \\n Ordenando...`date` \\n "
sort +0 -n $1>cu.dat
mv cu.dat $fourcol

##while [ $top -le $fim ];
##do
##awk 'NR>'$bot' && NR<='$top' {print $1,$2,$3,$4}' $tmpfour | sort +0 -n >>$fourcol
##	li=$((li+44));bot=$top;top=$((top+44));
##	#echo "BOT= $bot.  TOP=$top"
##done;
echo " \\n .........OK `date` \\n "
##
resul=`grep -c '*' $fourcol`
echo " \\n Resultado da analise de lixo (*): $resul \\n "


head -n3 espectro_medio2.f>COCO
cat<<eof1>>COCO
	PROGRAM MEDIOSPC2
        PARAMETER(L=$L,B=$BANDAS)
	REAL SSv,SSu,SSw,fm
	REAL SUMF,SUMU,SUMV,SUMW
	REAL DATA(L,4)
	integer i
	i=1
! arquivo de entrada de dados
        OPEN(UNIT=54,FILE='$fourcol')
!arquivo de saida dos espectros medios
        OPEN(UNIT=10,FILE='cM$1')

eof1
awk 'NR>3{print $0}' espectro_medio2.f>>COCO
data=`date`
cat<<eofcoco>>COCO

!=====================================================================
! source generated by Microm2006 - HANS/LUMET
! $data
!=====================================================================

eofcoco
echo " \\n compilando ... \\n "
mv COCO COCO.f
 rm spcmedio.x77
 g77 -o spcmedio.x77 COCO.f
 chmod +x spcmedio.x77
 echo " \\n executando... \\n "
 ./spcmedio.x77
cat cM$1 >> M$tip-$classe-$anomes.spc
## APNEDAR ANTES DE CHAMAR GERAGPL
# geragpl

#gv M$BANDAS-$classe-$anomes.pdf &
fi